baseURL = "https://theknightsoftheshrimpjesus.netlify.app/"
languageCode = "en-us"
title = "The Knights of the Shrimp Jesus"
theme = "archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	customcss = ["css/jesus.css"]

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "about"
url = "/about"
weight = 3


